version: "3.7"
services:  
  jerotoma_sms:
    container_name: jerotoma_sms  
    build:
      context: .
      dockerfile: Dockerfile
    image: jerotoma_sms
    ports:
      - "8082:8080"
    networks:
      - jerotoma_sms_net
    volumes:
      - type: bind
        source: ./JSMSServer/JSMSApplication/target/classes
        target: /usr/local/app/jerotoma_sms/JSMSServer/classes    
      - type: bind
        source: ./JSMSServer/JSMSApplication/target/dependency
        target: /usr/local/app/jerotoma_sms/JSMSServer/lib
      - type: bind
        source: ./tomcat/logs
        target: /usr/local/app/logs       
      - type: bind
        source: ./tomcat/jerotoma_sms/resources
        target: /usr/local/app/jerotoma_sms/resources   
networks:
  jerotoma_sms_net:
    name: jerotoma_sms_net

