version: "3.7"
services:
  jerotoma_sms:
    container_name: jerotoma_sms_dev   
    build:
      context: .
      dockerfile: Dockerfile.Development
    image: jerotoma_sms_dev
    ports:
      - "8082:8080"
    networks:
      - jerotoma_sms_dev_net
    volumes:
      - type: bind
        source: ./JSMSServer/JSMSApplication/target/classes
        target: /usr/local/app/jeretoma_sms/app/classes    
      - type: bind
        source: ./JSMSServer/JSMSApplication/target/dependency
        target: /usr/local/app/jeretoma_sms/app/lib
      - type: bind
        source: ./tomcat/logs
        target: /usr/local/app/logs       
      - type: bind
        source: ./tomcat/jerotoma_sms/resources
        target: /usr/local/app/jeretoma_sms/resources   
networks:
  jerotoma_sms_dev_net:
    name: jerotoma_sms_dev_net

